# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_designer\mainWindow.ui'
#
# Created: Sat Mar 10 02:24:46 2018
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(427, 440)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_Main = QtGui.QWidget(MainWindow)
        self.widget_Main.setAutoFillBackground(False)
        self.widget_Main.setObjectName("widget_Main")
        self.verticalLayout = QtGui.QVBoxLayout(self.widget_Main)
        self.verticalLayout.setObjectName("verticalLayout")
        self.layoutH__ImageContainer = QtGui.QHBoxLayout()
        self.layoutH__ImageContainer.setObjectName("layoutH__ImageContainer")
        self.treeWidget_dirTree = QtGui.QTreeWidget(self.widget_Main)
        self.treeWidget_dirTree.setRootIsDecorated(True)
        self.treeWidget_dirTree.setExpandsOnDoubleClick(True)
        self.treeWidget_dirTree.setObjectName("treeWidget_dirTree")
        self.treeWidget_dirTree.headerItem().setText(0, "1")
        self.treeWidget_dirTree.header().setVisible(False)
        self.layoutH__ImageContainer.addWidget(self.treeWidget_dirTree)
        self.label_pixmapContainer = QtGui.QLabel(self.widget_Main)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_pixmapContainer.sizePolicy().hasHeightForWidth())
        self.label_pixmapContainer.setSizePolicy(sizePolicy)
        self.label_pixmapContainer.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pixmapContainer.setObjectName("label_pixmapContainer")
        self.layoutH__ImageContainer.addWidget(self.label_pixmapContainer)
        self.layoutH__ImageContainer.setStretch(0, 4)
        self.layoutH__ImageContainer.setStretch(1, 10)
        self.verticalLayout.addLayout(self.layoutH__ImageContainer)
        self.layoutH_LogContainer = QtGui.QHBoxLayout()
        self.layoutH_LogContainer.setObjectName("layoutH_LogContainer")
        self.textarea_LogDisplay = QtGui.QTextEdit(self.widget_Main)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textarea_LogDisplay.sizePolicy().hasHeightForWidth())
        self.textarea_LogDisplay.setSizePolicy(sizePolicy)
        self.textarea_LogDisplay.setReadOnly(True)
        self.textarea_LogDisplay.setHtml("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>")
        self.textarea_LogDisplay.setObjectName("textarea_LogDisplay")
        self.layoutH_LogContainer.addWidget(self.textarea_LogDisplay)
        self.verticalLayout.addLayout(self.layoutH_LogContainer)
        self.verticalLayout.setStretch(0, 12)
        self.verticalLayout.setStretch(1, 2)
        MainWindow.setCentralWidget(self.widget_Main)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 427, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuNew = QtGui.QMenu(self.menuFile)
        self.menuNew.setObjectName("menuNew")
        self.menuOpen_Recent_Project = QtGui.QMenu(self.menuFile)
        self.menuOpen_Recent_Project.setObjectName("menuOpen_Recent_Project")
        self.menuConvert = QtGui.QMenu(self.menubar)
        self.menuConvert.setObjectName("menuConvert")
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew_Image = QtGui.QAction(MainWindow)
        self.actionNew_Image.setObjectName("actionNew_Image")
        self.actionConvert = QtGui.QAction(MainWindow)
        self.actionConvert.setObjectName("actionConvert")
        self.actionClear_Log = QtGui.QAction(MainWindow)
        self.actionClear_Log.setObjectName("actionClear_Log")
        self.actionNew_Project = QtGui.QAction(MainWindow)
        self.actionNew_Project.setObjectName("actionNew_Project")
        self.actionOpen_Project = QtGui.QAction(MainWindow)
        self.actionOpen_Project.setObjectName("actionOpen_Project")
        self.actionNo_recent_projects = QtGui.QAction(MainWindow)
        self.actionNo_recent_projects.setObjectName("actionNo_recent_projects")
        self.menuNew.addAction(self.actionNew_Image)
        self.menuOpen_Recent_Project.addAction(self.actionNo_recent_projects)
        self.menuFile.addAction(self.actionNew_Project)
        self.menuFile.addAction(self.actionOpen_Project)
        self.menuFile.addAction(self.menuOpen_Recent_Project.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.menuNew.menuAction())
        self.menuConvert.addAction(self.actionConvert)
        self.menuEdit.addAction(self.actionClear_Log)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuConvert.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "WF2HTML", None, QtGui.QApplication.UnicodeUTF8))
        self.label_pixmapContainer.setText(QtGui.QApplication.translate("MainWindow", "Create a project ( Ctrl + Shift + N )", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuNew.setTitle(QtGui.QApplication.translate("MainWindow", "New Image", None, QtGui.QApplication.UnicodeUTF8))
        self.menuOpen_Recent_Project.setTitle(QtGui.QApplication.translate("MainWindow", "Open Recent Project", None, QtGui.QApplication.UnicodeUTF8))
        self.menuConvert.setTitle(QtGui.QApplication.translate("MainWindow", "Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEdit.setTitle(QtGui.QApplication.translate("MainWindow", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_Image.setText(QtGui.QApplication.translate("MainWindow", "New Image", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_Image.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConvert.setText(QtGui.QApplication.translate("MainWindow", "Convert", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClear_Log.setText(QtGui.QApplication.translate("MainWindow", "Clear Log", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_Project.setText(QtGui.QApplication.translate("MainWindow", "New Project", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_Project.setToolTip(QtGui.QApplication.translate("MainWindow", "New Project", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_Project.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+N", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_Project.setText(QtGui.QApplication.translate("MainWindow", "Open Project", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_Project.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Shift+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNo_recent_projects.setText(QtGui.QApplication.translate("MainWindow", "No recent projects", None, QtGui.QApplication.UnicodeUTF8))

